Card.create!(card_name: 'Advance to "Go"', card_text: 'Collect $200', card_type: 'Community Chest', method_name: "advance_to_go", default_quantity: 1)
Card.create!(card_name: 'Bank error in your favor.', card_text: 'Collect $200', card_type: 'Community Chest', method_name: "", default_quantity: 1)
Card.create!(card_name: "Doctor's fees.", card_text: 'Pay $50', card_type: 'Community Chest', method_name: "", default_quantity: 1)
Card.create!(card_name: 'From sale of stock you get $50.', card_text: 'Collect $50', card_type: 'Community Chest', method_name: "", default_quantity: 1)
Card.create!(card_name: 'Get Out of Jail Free', card_text: 'This card may be kept until needed or sold/traded.', card_type: 'Community Chest', method_name: "", default_quantity: 1)
Card.create!(card_name: 'Go to Jail.', card_text: 'Go directly to jail. Do not pass Go, Do not collect $200.', card_type: 'Community Chest', method_name: "", default_quantity: 1)
Card.create!(card_name: 'Grand Opera Night', card_text: 'Collect $50 from every player for opening night seats.', card_type: 'Community Chest', method_name: "", default_quantity: 1)
Card.create!(card_name: 'Holiday Fund matures.', card_text: 'Receive $100.', card_type: 'Community Chest', method_name: "", default_quantity: 1)
Card.create!(card_name: 'Income tax refund.', card_text: 'Collect $20', card_type: 'Community Chest', method_name: "", default_quantity: 1)
Card.create!(card_name: 'It is your birthday.', card_text: 'Collect $10 from every player.', card_type: 'Community Chest', method_name: "", default_quantity: 1)
Card.create!(card_name: 'Life insurance matures', card_text: 'Collect $100', card_type: 'Community Chest', method_name: "", default_quantity: 1)
Card.create!(card_name: 'Hospital Fees', card_text: 'Pay $50', card_type: 'Community Chest', method_name: "", default_quantity: 1)
Card.create!(card_name: 'School fees.', card_text: 'Pay $50', card_type: 'Community Chest', method_name: "", default_quantity: 1)
Card.create!(card_name: 'Receive $25 consultancy fee.', card_text: 'Collect $25', card_type: 'Community Chest', method_name: "", default_quantity: 1)
Card.create!(card_name: 'You are assessed for street repairs:', card_text: 'Pay $40 per house and $115 per hotel you own.', card_type: 'Community Chest', method_name: "", default_quantity: 1)
Card.create!(card_name: 'You have won second prize in a beauty contest.', card_text: 'Collect $10', card_type: 'Community Chest', method_name: "", default_quantity: 1)
Card.create!(card_name: 'You inherit $100.', card_text: 'Collect $100', card_type: 'Community Chest', method_name: "", default_quantity: 1)