Space.create!(space_name: 'New York Avenue', space_cost: 100, rent_level1: 16, group: "orange",space_type: "residential", default_position: 20)
Space.create!(space_name: 'Tennessee Avenue', space_cost: 90, rent_level1: 14, group: "orange",space_type: "residential", default_position: 19)
Space.create!(space_name: 'St. James Place', space_cost: 90, rent_level1: 14, group: "orange",space_type: "residential", default_position: 17)
Space.create!(space_name: 'Illinois Avenue', space_cost: 120, rent_level1: 20, group: "red",space_type: "residential", default_position: 25)
Space.create!(space_name: 'Kentucky Avenue', space_cost: 110, rent_level1: 18, group: "red",space_type: "residential", default_position: 22)
Space.create!(space_name: 'Reading Railroad', space_cost: 100, rent_level1: 16, group: "orange",space_type: "residential", default_position: 6)
# Space.create!(space_name: 'New York Avenue', space_cost: 100, rent_level1: 25, group: "railroad",space_type: "railroad", default_position: 7)
Space.create!(space_name: 'Connecticut Avenue', space_cost: 60, rent_level1: 8, group: "light-blue",space_type: "residential", default_position: 10)
Space.create!(space_name: 'Indiana Avenue', space_cost: 110, rent_level1: 18, group: "red",space_type: "residential", default_position: 24)
Space.create!(space_name: 'Pennsylvania Railroad', space_cost: 100, rent_level1: 25, group: "railroad",space_type: "railroad", default_position: 16)
Space.create!(space_name: 'Atlantic Avenue', space_cost: 130, rent_level1: 22, group: "yellow",space_type: "residential", default_position: 27)
Space.create!(space_name: 'Ventnor Avenue', space_cost: 130, rent_level1: 22, group: "yellow",space_type: "residential", default_position: 28)
Space.create!(space_name: 'Boardwalk', space_cost: 200, rent_level1: 50, group: "blue",space_type: "residential", default_position: 40)
Space.create!(space_name: 'Vermont Avenue', space_cost: 50, rent_level1: 6, group: "light-blue",space_type: "residential", default_position: 9)
Space.create!(space_name: 'B. & O. Railroad', space_cost: 100, rent_level1: 25, group: "railroad",space_type: "railroad", default_position: 26)
Space.create!(space_name: 'States Avenue', space_cost: 70, rent_level1: 10, group: "purple",space_type: "residential", default_position: 14)
Space.create!(space_name: 'St. Charles Place', space_cost: 70, rent_level1: 10, group: "purple",space_type: "residential", default_position: 12)
Space.create!(space_name: 'Marvin Gardens', space_cost: 140, rent_level1: 24, group: "yellow",space_type: "residential", default_position: 30)
Space.create!(space_name: 'Short Line R.R', space_cost: 100, rent_level1: 25, group: "railroad",space_type: "railroad", default_position: 36)
Space.create!(space_name: 'Virginia Avenue', space_cost: 80, rent_level1: 12, group: "purple",space_type: "residential", default_position: 15)
Space.create!(space_name: 'Oriental Avenue', space_cost: 50, rent_level1: 6, group: "light-blue",space_type: "residential", default_position: 7)
Space.create!(space_name: 'Baltic Avenue', space_cost: 30, rent_level1: 4, group: "brown",space_type: "residential", default_position: 4)
Space.create!(space_name: 'Park Place', space_cost: 175, rent_level1: 35, group: "blue",space_type: "residential", default_position: 38)
Space.create!(space_name: 'Water Works', space_cost: 75, rent_level1: (rand(6) + 1) * 4, group: "utility",space_type: "utility", default_position: 29)
#dice roll times 4 if one owned, if two owned times 10
Space.create!(space_name: 'Mediterranean Avenue', space_cost: 30, rent_level1: 2, group: "brown",space_type: "residential", default_position: 2)
Space.create!(space_name: 'North Carolina Avenue', space_cost: 150, rent_level1: 26, group: "green",space_type: "residential", default_position: 33)
Space.create!(space_name: 'Electric Company', space_cost: 75, rent_level1: (rand(6) + 1) * 4, group: "utility",space_type: "residential", default_position: 13)
#dice roll times 4 if one owned, if two owned times 10
Space.create!(space_name: 'Pacific Avenue', space_cost: 150, rent_level1: 26, group: "green",space_type: "residential", default_position: 32)
Space.create!(space_name: 'Pennsylvania Avenue', space_cost: 160, rent_level1: 28, group: "green",space_type: "residential", default_position: 35)
